Nonkube sites enhancement to use namespaces (#1641)
* Applied nonkube namespace patch on top of v2

* Updated bootstrap script

* Fixed multiple namespaces validation
* Site bundles working properly

* Fixed test issues

* Updated README and reusing namespaces to produce tokens

* Small adjustements to nonkube README

* Dynamic suffix added to router names

* Saving status to processed resources

* Bundle generation does not conflict with existing namespaces

* Display namespace used by bundle and language change from token to static link

* Reload existing namespace

* Boostrap script can handle namespaces

* Bootstrap now uses bundle strategy as a flag

* Updated README and fixed some bugs

* Fixed issue listing containers

* Updated README

* Updated bootstrap script usage

* Updated remove script to use XDG variables

* Fixed unit test for compat client container list

* Creating systemd service directory

* Addressed initial feedback

* Static tokens generated for bind host and for each SAN

* Updated config renderer test to validate static links per host

* Improved output of remove.sh script

diff --git a/internal/nonkube/bundle/install.sh.template b/internal/nonkube/bundle/install.sh.template
--- a/internal/nonkube/bundle/install.sh.template
+++ b/internal/nonkube/bundle/install.sh.template
@@ -8,10 +8,14 @@ set -Ceu
 
 # site name to be provided by bundle generation
 export SITE_NAME="{{.SiteName}}"
-export SKUPPER_PLATFORM="podman"
+export SOURCE_NAMESPACE="{{.Namespace}}"
+export SOURCE_PLATFORM="{{.Platform}}"
+export NAMESPACE="${SOURCE_NAMESPACE}"
+export SKUPPER_PLATFORM="{{.Platform}}"
 export PLATFORM_COMMAND="podman"
 export REMOVE=false
 export DUMP_TOKENS=false
+export VERSION="{{.Version}}"
 
 # standard output directories
 if [ -z "${UID:-}" ]; then
@@ -33,8 +37,8 @@ if [ "${UID}" -eq 0 ]; then
     # shellcheck disable=SC2089
     export USERNS="''"
 fi
-export SITES_PATH="${SKUPPER_OUTPUT_PATH}/sites"
-export PLATFORM_FILE="${SITES_PATH}/${SITE_NAME}/runtime/state/platform.yaml"
+export NAMESPACES_PATH="${SKUPPER_OUTPUT_PATH}/namespaces"
+export PLATFORM_FILE="${NAMESPACES_PATH}/${NAMESPACE}/runtime/state/platform.yaml"
 export USER="${USER:-$(id -un)}"
 SITE_ID="$(hostname -s)-${USER}-$(date +%s)"
 export SITE_ID
@@ -46,14 +50,15 @@ exit_error() {
 
 usage() {
     echo "Usage: $0 [-p <podman|docker|systemd>] [-x] [-d <output-dir>]" >&2
-    echo "    -p    platform to use (one of: podman, docker, systemd)" >&2
+    echo "    -p    the platform to use: podman, docker, systemd (default: ${SOURCE_PLATFORM})" >&2
+    echo "    -n    target namespace (default: ${SOURCE_NAMESPACE})" >&2
     echo "    -x    remove existing site definition" >&2
-    echo "    -d    dump tokens from bundle to the provide output directory" >&2
+    echo "    -d    dump static links from bundle into the provide output directory" >&2
     exit 1
 }
 
 parse_opts() {
-    while getopts "xhd:p:" opt; do
+    while getopts "xhd:p:n:" opt; do
         case "${opt}" in
             p)
                 valid_platforms="podman docker systemd"
@@ -69,17 +74,12 @@ parse_opts() {
                     echo "Invalid platform: ${SKUPPER_PLATFORM}"
                     usage
                 fi
-                if [ "${SKUPPER_PLATFORM}" = "docker" ]; then
-                    export PLATFORM_COMMAND="docker"
-                    if [ "${UID}" -ne 0 ]; then
-                        # shellcheck disable=SC2090
-                        export USERNS="host"
-                    fi
-                    docker_gid=$(getent group docker | cut -d: -f3)
-                    export RUNAS="${UID}:${docker_gid}"
-                elif [ "${SKUPPER_PLATFORM}" = "systemd" ]; then
-                    export PLATFORM_COMMAND="skrouterd"
+                ;;
+            n)
+                if [ -n "${OPTARG}" ]; then
+                    export NAMESPACE="${OPTARG}"
                 fi
+                export PLATFORM_FILE="${NAMESPACES_PATH}/${NAMESPACE}/runtime/state/platform.yaml"
                 ;;
             d)
                 export DUMP_TOKENS=true
@@ -89,7 +89,7 @@ parse_opts() {
                     usage
                 fi
                 if [ ! -w "${SKUPPER_TOKEN_OUTPUT_PATH}" ]; then
-                    echo "No permission to write tokens to provided output directory"
+                    echo "No permission to write static links into the provided output directory"
                     usage
                 fi
                 ;;
@@ -104,15 +104,28 @@ parse_opts() {
                 ;;
         esac
     done
+
+    if [ "${SKUPPER_PLATFORM}" = "docker" ]; then
+        export PLATFORM_COMMAND="docker"
+        if [ "${UID}" -ne 0 ]; then
+            # shellcheck disable=SC2090
+            export USERNS="host"
+        fi
+        docker_gid=$(getent group docker | cut -d: -f3)
+        export RUNAS="${UID}:${docker_gid}"
+    elif [ "${SKUPPER_PLATFORM}" = "systemd" ]; then
+        export PLATFORM_COMMAND="skrouterd"
+    fi
+
 }
 
 create_service() {
     # if systemd is not available, skip it
     ${SYSTEMCTL} list-units > /dev/null 2>&1 || return
-    service_name="skupper-site-${SITE_NAME}.service"
+    service_name="skupper-${NAMESPACE}.service"
     service_file_suffix="container"
     [ "${SKUPPER_PLATFORM}" = "systemd" ] && service_file_suffix="systemd"
-    service_file="${SKUPPER_OUTPUT_PATH}/sites/${SITE_NAME}/runtime/scripts/${service_name}.${service_file_suffix}"
+    service_file="${SKUPPER_OUTPUT_PATH}/namespaces/${NAMESPACE}/runtime/scripts/skupper.service.${service_file_suffix}"
 
     if [ ! -f "${service_file}" ]; then
         echo "SystemD service has not been defined"
@@ -124,8 +137,7 @@ create_service() {
         cp "${service_file}" "/etc/systemd/system/${service_name}"
     else
         if [ ! -d "${SERVICE_DIR}" ]; then
-            echo "Unable to define path to SystemD service"
-            return
+            mkdir -p "${SERVICE_DIR}"
         fi
         cp "${service_file}" "${SERVICE_DIR}/${service_name}"
     fi
@@ -135,50 +147,56 @@ create_service() {
 }
 
 remove_service() {
-    service="skupper-site-${SITE_NAME}.service"
-    ${SYSTEMCTL} stop ${service}
-    ${SYSTEMCTL} disable ${service}
+    service="skupper-${NAMESPACE}.service"
+    ${SYSTEMCTL} stop "${service}"
+    ${SYSTEMCTL} disable "${service}"
     rm -f "${SERVICE_DIR:?}/${service}"
     ${SYSTEMCTL} daemon-reload
     ${SYSTEMCTL} reset-failed
 }
 
 remove_site() {
-    if [ ! -d "${SITES_PATH}/${SITE_NAME}" ]; then
-        echo "Site \"${SITE_NAME}\" does not exist"
+    if [ ! -d "${NAMESPACES_PATH}/${NAMESPACE}" ]; then
+        echo "Namespace \"${NAMESPACE}\" does not exist"
         exit 0
     fi
 
-    echo "Removing Skupper site definition for: ${SITE_NAME}"
+    SITE_PATH="${NAMESPACES_PATH}/${NAMESPACE}/runtime/state/site/"
+    if ! grep -qr "name: ${SITE_NAME}\$" "${SITE_PATH}"; then
+        echo "Site \"${SITE_NAME}\" is not defined on namespace \"${NAMESPACE}\""
+        exit 0
+    fi
+
+    echo "Removing Skupper site definition for ${SITE_NAME} from namespace ${NAMESPACE}"
     SKUPPER_PLATFORM=$(grep '^platform: ' "${PLATFORM_FILE}" | sed -e 's/.*: //g')
     if [ "${SKUPPER_PLATFORM}" != "systemd" ]; then
         # removing router container
-        ${SKUPPER_PLATFORM} rm -f ${SITE_NAME}-skupper-router
+        ${SKUPPER_PLATFORM} rm -f "${NAMESPACE}-skupper-router"
     fi
     # removing site definition
-    rm -rf "${SITES_PATH:?}/${SITE_NAME:?}/"
+    rm -rf "${NAMESPACES_PATH:?}/${NAMESPACE:?}/"
 }
 
 dump_tokens() {
-    tokens="$(ls "./${SITE_NAME}/runtime/token/")"
+    tokens="$(ls "./${SOURCE_NAMESPACE}/runtime/link/")"
     if [ -z "${tokens}" ]; then
-        echo "No tokens defined in this site bundle"
+        echo "No static links defined in this site bundle"
         return
     fi
     token_out_dir="${SKUPPER_TOKEN_OUTPUT_PATH:?}/${SITE_NAME:?}"
     mkdir -p "${token_out_dir}"
-    cp "./${SITE_NAME}/runtime/token/"*.yaml "${token_out_dir}"
-    echo "Tokens for site \"${SITE_NAME}\" have been saved into ${token_out_dir}"
+    cp "./${SOURCE_NAMESPACE}/runtime/link/"*.yaml "${token_out_dir}"
+    echo "Static links for site \"${SITE_NAME}\" have been saved into ${token_out_dir}"
 }
 
 set_router_access_port() {
-    config_file="${SITES_PATH}/${SITE_NAME}/config/router/skrouterd.json"
-    python "${SITES_PATH:?}/${SITE_NAME:?}/runtime/scripts/router_free_port.py" "${config_file}"
+    config_file="${NAMESPACES_PATH}/${NAMESPACE}/config/router/skrouterd.json"
+    python "${NAMESPACES_PATH:?}/${NAMESPACE:?}/runtime/scripts/router_free_port.py" "${config_file}"
 }
 
 create_sed_script() {
     ssl_profile_base_path="\${SSL_PROFILE_BASE_PATH}"
-    [ "${SKUPPER_PLATFORM}" = "systemd" ] && ssl_profile_base_path="${SITES_PATH}/${SITE_NAME}"
+    [ "${SKUPPER_PLATFORM}" = "systemd" ] && ssl_profile_base_path="${NAMESPACES_PATH}/${NAMESPACE}"
     container_engine="podman"
     [ "${SKUPPER_PLATFORM}" != "systemd" ] && container_engine="${SKUPPER_PLATFORM}"
     # populating sed script
@@ -187,53 +205,58 @@ create_sed_script() {
     # shellcheck disable=SC1083
     {
         echo "s#{{"{{"}}.SiteNameSuffix{{"}}"}}#${SITE_ID}#g"
+        echo "s#{{"{{"}}.Namespace{{"}}"}}#${NAMESPACE}#g"
         echo "s#{{"{{"}}.Platform{{"}}"}}#${SKUPPER_PLATFORM}#g"
         echo "s#{{"{{"}}.SslProfileBasePath{{"}}"}}#${ssl_profile_base_path}#g"
         echo "s#{{"{{"}}.ContainerEngine{{"}}"}}#${container_engine}#g"
         echo "s#{{"{{"}}.SiteId{{"}}"}}#${SITE_ID}#g"
-        echo "s#{{"{{"}}.SitesPath{{"}}"}}#${SITES_PATH}#g"
+        echo "s#{{"{{"}}.NamespacesPath{{"}}"}}#${NAMESPACES_PATH}#g"
         echo "s#{{"{{"}}.RuntimeDir{{"}}"}}#${RUNTIME_DIR}#g"
-        echo "s#{{"{{"}}.SiteScriptPath{{"}}"}}#${SITES_PATH}/${SITE_NAME}/runtime/scripts#g"
-        echo "s#{{"{{"}}.SiteConfigPath{{"}}"}}#${SITES_PATH}/${SITE_NAME}/config/router#g"
+        echo "s#{{"{{"}}.SiteScriptPath{{"}}"}}#${NAMESPACES_PATH}/${NAMESPACE}/runtime/scripts#g"
+        echo "s#{{"{{"}}.SiteConfigPath{{"}}"}}#${NAMESPACES_PATH}/${NAMESPACE}/config/router#g"
         echo "s#{{"{{"}}.RunAs{{"}}"}}#${RUNAS}#g"
         echo "s#{{"{{"}}.UserNamespace{{"}}"}}#${USERNS}#g"
     } >> script.sed
 }
 
 render_sed_templates() {
-    grep -rl '{{"{{"}}' "${SITES_PATH}/${SITE_NAME}" | xargs -r -i sed -f script.sed -i {}
+    grep -rl '{{"{{"}}' "${NAMESPACES_PATH}/${NAMESPACE}" | xargs -r -i sed -f script.sed -i {}
     rm -f script.sed
 }
 
 show_token_info() {
-    token_path="${SITES_PATH:?}/${SITE_NAME:?}/runtime/token"
+    token_path="${NAMESPACES_PATH:?}/${NAMESPACE:?}/runtime/link"
     [ ! -d "${token_path}" ] && return
     tokens_found=$(find "${token_path}" -type f | wc -l)
     if [ "${tokens_found}" -gt 0 ]; then
-        echo "Static tokens have been defined at: ${token_path}"
+        echo "Static links have been defined at: ${token_path}"
     fi
 }
 
 create_containers() {
     [ "${SKUPPER_PLATFORM}" = "systemd" ] && return
-    "${SITES_PATH:?}/${SITE_NAME:?}/runtime/scripts/containers_create.sh"
+    "${NAMESPACES_PATH:?}/${NAMESPACE:?}/runtime/scripts/containers_create.sh"
 }
 
 create_site() {
-    if [ -d "${SITES_PATH}/${SITE_NAME}" ]; then
-        echo "Failed: site \"${SITE_NAME}\" is already defined"
+    if [ -d "${NAMESPACES_PATH}/${NAMESPACE}" ]; then
+        echo "Failed: namespace \"${NAMESPACE}\" is already defined"
+        echo "Location: ${NAMESPACES_PATH}/${NAMESPACE}"
         exit 1
     fi
 
     echo "Skupper site bundle installation"
-    echo "Site name: ${SITE_NAME}"
-    echo "Platform : ${SKUPPER_PLATFORM}"
+    echo "Namespace : ${NAMESPACE}"
+    echo "Site name : ${SITE_NAME}"
+    echo "Platform  : ${SKUPPER_PLATFORM}"
+    echo "Definition: ${NAMESPACES_PATH:?}/${NAMESPACE:?}/sources"
+    echo "Version   : ${VERSION}"
 
     # Create base directory tree
-    mkdir -p "${SITES_PATH}"
+    mkdir -p "${NAMESPACES_PATH}"
 
     # Installing site definition files
-    cp -rf "./${SITE_NAME}" "${SITES_PATH}/${SITE_NAME}"
+    cp -rf "./${SOURCE_NAMESPACE}" "${NAMESPACES_PATH}/${NAMESPACE}"
 
     # Creating platform.yaml
     echo "platform: ${SKUPPER_PLATFORM}" > "${PLATFORM_FILE}"
@@ -254,11 +277,11 @@ create_site() {
     # Create systemd service
     create_service
 
-    echo "Site \"${SITE_NAME}\" is now running"
+    echo "Site \"${SITE_NAME}\" is now running on namespace \"${NAMESPACE}\""
 }
 
 sanity_check() {
-    required_fields="SITE_NAME SKUPPER_OUTPUT_PATH SERVICE_DIR SITES_PATH SKUPPER_PLATFORM"
+    required_fields="SITE_NAME SOURCE_NAMESPACE NAMESPACE SKUPPER_OUTPUT_PATH SERVICE_DIR NAMESPACES_PATH SKUPPER_PLATFORM"
     required_commands="python sed find grep xargs tar getent id ${PLATFORM_COMMAND}"
 
     for field_name in ${required_fields}; do
